"""Report generation: Jinja2 rendering, PDF (WeasyPrint), DOCX (python-docx)."""
import io
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

logger = logging.getLogger(__name__)

_TEMPLATE_DIR = Path(__file__).parent / "templates"

# Whitelist of valid template IDs
VALID_TEMPLATES = {
    "standard": "standard_compliance.html",
    "executive_summary": "executive_summary.html",
    "detailed_analysis": "detailed_analysis.html",
}

_jinja_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(["html", "xml"]),
)


def validate_template_id(template_id: str) -> str:
    """Validate template_id against whitelist. Raises ValueError if invalid."""
    if template_id not in VALID_TEMPLATES:
        raise ValueError(
            f"Invalid template: {template_id!r}. "
            f"Valid templates: {', '.join(sorted(VALID_TEMPLATES))}"
        )
    return VALID_TEMPLATES[template_id]


def render_report(
    template_id: str,
    title: str,
    documents: list[dict],
    report_type: str = "standard",
    created_by: str | None = None,
) -> str:
    """Render a report to HTML using a Jinja2 template.

    All template variables are autoescaped to prevent XSS.
    """
    template_file = validate_template_id(template_id)
    template = _jinja_env.get_template(template_file)

    html = template.render(
        title=title,
        documents=documents,
        report_type=report_type,
        created_by=created_by,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )

    return html


def html_to_pdf(html_content: str) -> bytes:
    """Convert HTML to PDF using WeasyPrint with external URL fetching disabled.

    SECURITY: url_fetcher returns empty for all external resources to prevent SSRF.
    """
    from weasyprint import HTML

    def _sandboxed_url_fetcher(url: str, timeout=10, ssl_context=None):
        """Block all external resource fetching to prevent SSRF."""
        if url.startswith("data:"):
            # Allow data URIs (inline images etc.)
            from weasyprint import default_url_fetcher
            return default_url_fetcher(url, timeout=timeout, ssl_context=ssl_context)
        # Block everything else (http, https, file, ftp, etc.)
        logger.warning("Blocked external resource fetch in PDF: %s", url[:200])
        return {"string": b"", "mime_type": "text/plain"}

    pdf_bytes = HTML(
        string=html_content,
        url_fetcher=_sandboxed_url_fetcher,
    ).write_pdf()

    return pdf_bytes


def html_to_docx(html_content: str, title: str = "Compliance Report") -> bytes:
    """Convert structured data to DOCX using python-docx."""
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    heading = doc.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
    ).alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("")  # Spacer

    # Parse basic structure from HTML (simplified extraction)
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html_content, "html.parser")

    for heading_tag in soup.find_all(["h1", "h2", "h3"]):
        level = int(heading_tag.name[1])
        doc.add_heading(heading_tag.get_text(strip=True), level=level)

        # Add content after heading until next heading
        for sibling in heading_tag.next_siblings:
            if sibling.name in ("h1", "h2", "h3"):
                break
            if sibling.name == "p":
                doc.add_paragraph(sibling.get_text(strip=True))
            elif sibling.name == "ul":
                for li in sibling.find_all("li"):
                    doc.add_paragraph(li.get_text(strip=True), style="List Bullet")
            elif sibling.name == "table":
                rows = sibling.find_all("tr")
                if rows:
                    cols = len(rows[0].find_all(["th", "td"]))
                    table = doc.add_table(rows=len(rows), cols=cols)
                    table.style = "Table Grid"
                    for i, row in enumerate(rows):
                        cells = row.find_all(["th", "td"])
                        for j, cell in enumerate(cells):
                            if j < cols:
                                table.rows[i].cells[j].text = cell.get_text(strip=True)

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph("Generated by RegulatorAI Compliance Service.")
    footer.runs[0].font.size = Pt(8)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
